### PR TITLE
Fix broken maps

### PR DESCRIPTION
**Pull request by brunosan**
Still doesn't solve the issue. Account seems not ok.

cc @smit1678

### CODE REVIEW

**Comment by drewbo** [comment]
Looks like the account is disabled @brunosan 

screen shot 2016-07-22 at 12 06 32 pm

**Comment by brunosan** [comment]
I'll drop an email to help@mapbox.com cc @jjhurlock.

**Comment by geografa** [comment]
@brunosan Looking at your `stateofsatellite` message. Looks like the acct was either on a coupon or on a standard with extra storage and it ran out of credit. Sending you an email now through the ticket for further instructions.

**Comment by brunosan** [comment]
Thanks @geografa!

@drewbo I've forwarded you the instructions to unblock it for now (I don't have access to that email account). Once that's done maps should get fixed. 

This also closes #53 (Thanks @pythagoraswitch!!)

**Pull request merged**
